set(PROJECT_TYPE $<TARGET_PROPERTY:${PROJECT_NAME},TYPE>)
set(PROJECT_TYPE_RS $<IF:$<STREQUAL:${PROJECT_TYPE},EXECUTABLE>,[bin],lib>)

set(PROJECT_SOURCES $<TARGET_PROPERTY:${PROJECT_NAME},SOURCES>)
# FIXME: The following requires cmake 4.0+
#set(PROJECT_SOURCES_RS $<PATH:REPLACE_EXTENSION,${PROJECT_SOURCES},.rs>)
set(PROJECT_SOURCES_RS ${PROJECT_SOURCES}.rs)

file(GENERATE OUTPUT "Cargo.toml" CONTENT "[package]
name = \"${PROJECT_NAME}\"
version = \"0.1.0\"
edition = \"2024\"

[${PROJECT_TYPE_RS}]
name = \"${PROJECT_NAME}\"
path = \"${PROJECT_SOURCES_RS}\"
")
